spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none   # 또는 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
jwt:
  secret-key: ${JWT_SECRET_KEY:0VFd9UZwXwLVaX40nCLLGuqyx6tcWzGz+KGHpDz9G+xTVOfNLlqbh4YqfKbzzKDQl94OCqP1MLm6dNuLJdY8qg==}
  access-token-validity: 600000  # 10분
  refresh-token-validity: 604800000  # 7일
dev:
  enabled: true
  header-name: bypass-jwt-auth
  token: whisKey-dev
order:
  reservation:
    expire-time: 10
payment:
  compensation:
    retry-time: 5
toss:
  payment:
    secret-key: test_sk_pP2YxJ4K87apm2lqMegpVRGZwXLO
    client-key: test_ck_pP2YxJ4K87Z9dKKBg9y0rRGZwXLO
    base-url: https://api.tosspayments.com/v1
    connect-timeout: 3000
    read-timeout: 10000
logging:
  level:
    com.whiskey.payment: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG